### ISSUE TITLE
Unable to find dependency with gradle

### ISSUE THREAD

**Issue by robinroscher** [ChargeTimeEU/Java-OCA-OCPP#115] opened 2020-04-15 15:38 UTC
Hi, up until now we were using this library in one of our Spring applications, specifically the following commit:

[implementation 'com.github.ChargeTimeEU:Java-OCA-OCPP:a67719e'](https://github.com/ChargeTimeEU/Java-OCA-OCPP/commit/a67719e6e78d8d2d073984d609a10540d8c89594)

Now we need to implement **GetCompositeSchedule** and need a newer commit.
We tried to use the latest commit on master:

[implementation 'com.github.ChargeTimeEU:Java-OCA-OCPP:75671a2'](https://github.com/ChargeTimeEU/Java-OCA-OCPP/commit/75671a2d48355d44827e195531de43477c0f93d3)

and a few other earlier commits.

None of these commits worked for us as gradle does not find the dependency.

Looking at Jitpack we saw that on the master-SNAPSHOT branch the logfile has the following error:

```
> Task :OCPP-J:verifyGoogleJavaFormat FAILED

The following files are not formatted properly:

/home/jitpack/build/OCPP-J/src/main/java/eu/chargetime/ocpp/JSONCommunicator.java

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':OCPP-J:verifyGoogleJavaFormat'.
> Problems: formatting style violations
```
Could this be the issue for gradle not finding the dependency or is something wrong on our side? 

Maybe you already know this issue and could point us in the right direction to help and fix it?

Thanks!

**Comment by TVolden** [comment] 2020-04-15 17:54
Hi @robinroscher,

**Comment by TVolden** [comment] 2020-04-15 18:03
I can see that I accidentally closed the issue. Sorry about that

**Comment by robinroscher** [comment] 2020-04-16 08:04
Awesome thanks a lot! Hopefully this PR solves this issue

**Comment by TVolden** [comment] 2020-04-21 18:33
I have tried to clone and run the code on repl.it but I get some wierd errors from both maven and gradle when I try to build. Something with the XmlElements and soap attributes in general. Do you get those as well?

**Comment by robinroscher** [comment] 2020-04-22 09:50
I get errors with @XmlRootElement and @XmlElement annotations

**Comment by robinroscher** [comment] 2020-05-12 13:51
@TVolden After you merged this issue **#111** I could pull the build from Jitpack, however I then got a lot of errors because of the Date component. You mentioned to create a PR for it before closing the issue so it looks like you already know how to fix it. I still have issues with the `@XmlRootElement` and `@XmlElement` annotations and can not build the project to look into it myself.

Is there any chance this can be fixed soon?

We need to implement the **GetCompositeSchedule** as soon as possible and this is still blocking us.

**Comment by TVolden** [comment] 2020-05-13 14:42
Hi @robinroscher, I'm sorry. I though I had fixed the @XmlRootElement issue with the jitpack build.
I could recreate the problem on my local windows PC, but I get it when I use repl.it

I'll look into it right away.

**Comment by TVolden** [comment] 2020-05-13 16:17
Okay, I have imported packages to fix the problem and updated some that caused problems.
Please try again to see if this fixed your problem.

**Comment by robinroscher** [comment] 2020-05-15 14:59
Even though I dont have the `@XmlRootElement` and `@XmlElement` errors, I still have some other errors with importing `org.slfj4.Logger` and `org.slfj4.LoggerFactory`  where I am not sure if they are on my side.

But I just noticed that your latest commit works on Jitpack for the **_OCPP-J_** module:
**`implementation 'com.github.ChargeTimeEU.Java-OCA-OCPP:OCPP-J:ecaceb4641'`**
but is broken for the version: **`master-SNAPSHOT`**

I am not sure why a commit builds only a submodule on Jitpack, am I missing something?

**Comment by TVolden** [comment] 2020-05-15 18:57
I haven't experienced problems related to logging. But maybe they need to be bumped up to a newer version?
I have some problems with Maven integration tests on my local pc. Im suspecting it's caused by my change to openjdk.

Which java jdk do you use?

**Comment by e-power** [comment] 2020-05-18 08:03
> Which java jdk do you use?
If you mean the Java-OCA-OCPP project I am trying with Java 11.

So, are the failing maven integration tests the reason why the **master-SNAPSHOT** branch fails on Jitpack?

**Comment by robinroscher** [comment] 2020-05-18 08:05
> Which java jdk do you use?

If you mean the Java-OCA-OCPP project I am trying with Java 11.

So, are the failing maven integration test the reason for the master branch to fail on Jitpack?

**Comment by TVolden** [comment] 2020-05-18 09:49
Hi @robinroscher 

Hmm, it looked like a locked resource caused the problem, I have rerun the build and now it's green.

**Comment by robinroscher** [comment] 2020-05-18 13:06
Hi @TVolden 
Maybe we are not talking about the same thing? For me it still shows as failed:

![image](https://user-images.githubusercontent.com/19746903/82216202-e34d9a00-9918-11ea-9797-2e374cb822be.png)

**Comment by TVolden** [comment] 2020-05-20 05:30
Hi @robinroscher,

I have tried to find the result you get on jitpack, but it's green on mine?

This is where i look:
https://jitpack.io/#ChargeTimeEU/Java-OCA-OCPP

Is it still red on yours? Can you send a link?

**Comment by robinroscher** [comment] 2020-05-20 11:30
I don't know what happened there, now I also see it green and can pull it!

**Comment by TVolden** [comment] 2020-05-24 16:11
Hi @robinroscher 

Does that mean that this issue is resolved? If so, can I get you to close it?

Sincerely, 
Thomas

**Closed** 2020-05-25 06:48 UTC
