### ISSUE TITLE
NPE during offline mode

### ISSUE THREAD

**Issue by sumlin** [ChargeTimeEU/Java-OCA-OCPP#25] opened 2017-11-14 23:47 UTC
java.lang.NullPointerException
at eu.chargetime.ocpp.Client$1.handleError(Client.java:98)
at eu.chargetime.ocpp.Session$CommunicatorEventHandler.onError(Session.java:178)
at eu.chargetime.ocpp.Communicator.sendCall(Communicator.java:169)
at eu.chargetime.ocpp.Session.sendRequest(Session.java:77)
at eu.chargetime.ocpp.Client.send(Client.java:146)

Client.send()
String id = session.sendRequest(feature.getAction(), request);

Session.sendRequest()
communicator.sendCall(uuid, action, payload);

Communicator.sendCall() -> NotConnectedException ex -> request is NOT transaction related
events.onError()

Session$CommunicatorEventHandler.onError()
events.handleError(id, errorCode, errorDescription, payload);

getPromise(uniqueId) method returns null, because Client.send() puts the uniqueId on the next line (by createPromise(id)).

How to reproduce:
1) Block a connection to server's port by iptables -A INPUT -i lo -p tcp -m tcp --dport 8080 -j DROP
2) Made a sync-safe connect() after disconnect(). 

        cl.sendBootNotificationRequest();
        delay(5);
        cl.sendStartTransactionRequest(1, "idTag");
        delay(10);
        cl.sendHeartbeatRequest();
        delay(150);

Solution: for my (it might be acceptable only for my async) code it works:

```
diff --git a/ocpp-common/src/main/java/eu/chargetime/ocpp/Session.java b/ocpp-common/src/main/java/eu/chargetime/ocpp/Session.java           
index 20d4739..c69fd14 100644                                                                                                                
--- a/ocpp-common/src/main/java/eu/chargetime/ocpp/Session.java                                                                              
+++ b/ocpp-common/src/main/java/eu/chargetime/ocpp/Session.java                                                                              
@@ -74,7 +74,7 @@ public class Session {
      */
     public String sendRequest(String action, Request payload) {
         String uuid = queue.store(payload);
-        communicator.sendCall(uuid, action, payload);
+        new Thread( () -> communicator.sendCall(uuid, action, payload) ).start();
         return uuid;
     }
```

P.S. I'm using all send* methods by async way. If i'd want to get sync method, I just execute .get() for a CompletableFuture<> object.

**Comment by TVolden** [comment] 2017-11-15 20:54
Hi,

I appreciate the work you put into finding and explaining this bug.

I agree that your solution would work, but it could turn the bug into a race condition. I have to study the code a little bit, but I think the problem is that Session.sendRequest actually does more than just "send request"... If i create one method to store a request and one to send a request, then I could play it safe in Client.send

**Comment by TVolden** [comment] 2017-11-15 21:24
Added a fix, please check if that fixed the issue.

**Comment by TVolden** [comment] 2017-12-14 07:24
Have you had a chance to test it?

**Comment by TVolden** [comment] 2018-02-21 20:43
OK. I'm closing the issue and consider it resolved. Please make a new issue if this is not the case.

**Closed by TVolden** 2018-02-21 20:43 UTC
