### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by JoJoBaer** [ChargeTimeEU/Java-OCA-OCPP#24] opened 2017-09-05 07:44 UTC
Hi,
I have implemented a central system service, but can't figure out how I should handle Exceptions that make it impossible to fulfil the request. When a runtime exception is thrown in my ServerCoreProfile, it does not send a response (I am using the SOAP server).

**Comment by TVolden** [comment] 2017-09-05 13:29
Hi,

Thanks for your feedback. 
Let's see if I understand your problem correctly.
You get a request and try to handle it.
Something goes wrong in your implementation of ServerCoreProfile and you throw an Exception.
Am I correct so far?

The exception isn't caught by the lib, so the client doesn't get a response. The request can't be recovered, so it's technically lost in limbo.

Am I correct in assuming, that you don't want to process the request, but actually want to send an error back to the client?

**Comment by JoJoBaer** [comment] 2017-09-05 20:21
Yes that's correct, I want to send an error response to the client.

**Comment by TVolden** [comment] 2017-09-05 20:46
Okay, I have examined the code again, to refresh my memory.
If you throw an Exception, this should be picked up by the SimpleRequestDispatcher class:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/d48dc5fc1d0d6ac9fd4b00c197e21492b3a69597/ocpp-common/src/main/java/eu/chargetime/ocpp/RequestDispatcher.java#L72-L75

The CompletableFuture should completeExceptionally, which should be picked up by the ConfirmationHandler class:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/d48dc5fc1d0d6ac9fd4b00c197e21492b3a69597/ocpp-common/src/main/java/eu/chargetime/ocpp/ConfirmatinHandler.java#L46-L47

The Confirmation handler should then return an error to the client.

**Comment by TVolden** [comment] 2017-09-06 21:18
Daily update

I have managed to provoke the error through test. It looks like the problem is only present for SOAP.
I'm looking into a solution.

**Comment by TVolden** [comment] 2017-09-07 20:42
Okay. I have located the problem and applied a fix. Please try again with the new version.
Please close the issue, if this fix resolved the problem.

Thanks again. :)

**Comment by JoJoBaer** [comment] 2017-09-09 07:24
That solved the problem, thanks!

**Closed** 2017-09-09 07:25 UTC
Labels: bug
